inertial_frame_id: world
waypoints:
  -
    point: [0, 12, -0.5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [16, 12, -0.5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [20, 12, -0.5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 16, -0.5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 20, -0.5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [30, 40, -0.5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [36, 45, -0.5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [60, 70, -0.5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [105, 56, -0.5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [100, -20, -0.5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [100, -20, -0.5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
